name: cs-divine-crm
services:
- name: web
  source_dir: /
  github:
    repo: cee396/cs-divine-crm
    branch: master
    deploy_on_push: true
  build_command: npm ci --legacy-peer-deps && npm run build
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 3000
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "3000"
  - key: DATABASE_URL
    value: "${DATABASE_URL}"
  - key: NEXTAUTH_URL
    value: "${NEXTAUTH_URL}"
  - key: NEXTAUTH_SECRET
    value: "${NEXTAUTH_SECRET}"
